name: dosing
# 测试的话打开这个来测试变量值之类的是否填写正确
#on:
#  push:  # 任何推送到仓库都会触发这个工作流

#on:
#  schedule:
#    - cron: '50 10 * * *' # 10对应的是北京时间晚上六点 50是分钟 表示每天晚上六点五十执行，可以改成任意时间测试
#
on:
  schedule: # 每周五、六的晚上九点执行 时差为 +8
    - cron: '0 13 * * 1,2,3,4,5,6'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pyexecjs requests pytz

      - name: Run python script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          python gzlg助手/dowork.py || echo "Script failed with exit code $?"
        
